---
  - hosts: proxmox

    vars_files:
      - 'vars/vault.yaml'
    
    pre_tasks:
      - name: Add users
        ansible.builtin.user:
          name: "{{ item.value.name }}"
          shell: "{{ item.value.shell }}"
          groups: "{{ item.value.groups }}"
          append: true
        with_dict: "{{ proxmox_users }}"
        
      - name: Install packages
        ansible.builtin.apt:
          name: "{{ apt_packages }}"
          update_cache: yes
          state: present
    
    roles:
      - role: ironicbadger.proxmox_nag_removal
      - role: tigattack.mergerfs
      - role: geerlingguy.docker
      - role: ironicbadger.snapraid
      - role: vladgh.samba.server
      - role: fuzzymistborn.autorestic
      - role: artis3n.tailscale

    tasks:
      - name: Copy docker-compose.yml
        ansible.posix.synchronize:
          src: 'vars/docker-compose.yml'
          dest: "{{ compose_config_path }}/docker-compose.yml"

      - name: Up new compose 
        ansible.builtin.shell:
          cmd: docker compose up -d
          chdir: "{{ compose_config_path }}"
        register: output

      - name: Print output
        debug:
          var: output