[project]
name = "laserv-infra"
revision = "1.0"

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }
ANSIBLE_VAULT_PASSWORD = { description = "Ansible vault password", providers = ["bitwarden"] }

[providers]
local_cache = "file://~/.cache/secretspec/"

# Use the standard Bitwarden vault provider with your cache attached
bitwarden = { 
  uri = "bw://",
  cache = { provider = "local_cache", max_age = "1h" } 
}
